name: validate docs to schema
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: snok/install-poetry@v1
      - name: validate
        run: poetry run python lib/validate_json_to_schema.py 